/*******************************************************************************
* WEB222 – Assignment 2
* I declare that this assignment is my own work in accordance with Seneca
* Academic Policy. No part of this assignment has been copied manually or
* electronically from any other source (including web sites) or distributed to
* other students.
*
* Name: Abhi Bansal Student ID: 122132210 Date: 02/09/2022
*
******************************************************************************/

//Part A

var people=[{"id":1,"first_name":"Betteann","last_name":"Vales","email":"bvales0@free.fr","gender":"Male","birthDate":"1/22/2000","web":"http://last.fm/blandit/ultrices/enim/lorem.xml?potenti=orci&in=mauris&eleifend=lacinia&quam=sapien&a=quis&odio=libero&in=nullam&hac=sit&habitasse=amet&platea=turpis&dictumst=elementum&maecenas=ligula&ut=vehicula&massa=consequat&quis=morbi&augue=a&luctus=ipsum&tincidunt=integer&nulla=a&mollis=nibh&molestie=in&lorem=quis&quisque=justo&ut=maecenas&erat=rhoncus&curabitur=aliquam&gravida=lacus&nisi=morbi&at=quis&nibh=tortor&in=id&hac=nulla&habitasse=ultrices&platea=aliquet&dictumst=maecenas&aliquam=leo&augue=odio&quam=condimentum&sollicitudin=id&vitae=luctus&consectetuer=nec&eget=molestie&rutrum=sed&at=justo&lorem=pellentesque&integer=viverra&tincidunt=pede&ante=ac&vel=diam&ipsum=cras&praesent=pellentesque&blandit=volutpat&lacinia=dui&erat=maecenas&vestibulum=tristique&sed=est&magna=et&at=tempus&nunc=semper&commodo=est&placerat=quam&praesent=pharetra&blandit=magna&nam=ac&nulla=consequat&integer=metus&pede=sapien&justo=ut&lacinia=nunc&eget=vestibulum&tincidunt=ante&eget=ipsum&tempus=primis&vel=in&pede=faucibus&morbi=orci&porttitor=luctus&lorem=et&id=ultrices&ligula=posuere&suspendisse=cubilia","creditScore":730,"rating":19},
    {"id":2,"first_name":"Sully","last_name":"Sharpous","email":"ssharpous1@mit.edu","gender":"Female","birthDate":"10/22/1995","web":"https://networksolutions.com/pulvinar/nulla/pede/ullamcorper/augue/a.js?sapien=dapibus&ut=duis&nunc=at&vestibulum=velit&ante=eu&ipsum=est&primis=congue&in=elementum&faucibus=in&orci=hac&luctus=habitasse&et=platea&ultrices=dictumst&posuere=morbi&cubilia=vestibulum&curae=velit&mauris=id&viverra=pretium&diam=iaculis&vitae=diam&quam=erat&suspendisse=fermentum&potenti=justo&nullam=nec&porttitor=condimentum&lacus=neque&at=sapien&turpis=placerat&donec=ante&posuere=nulla&metus=justo","creditScore":362,"rating":10},
    {"id":3,"first_name":"Hermia","last_name":"Stanex","email":"hstanex2@cnet.com","gender":"Genderfluid","birthDate":"4/13/1992","web":"https://google.com.au/varius/nulla/facilisi/cras.json?commodo=ultrices&placerat=posuere&praesent=cubilia&blandit=curae&nam=nulla&nulla=dapibus&integer=dolor&pede=vel&justo=est&lacinia=donec&eget=odio&tincidunt=justo&eget=sollicitudin&tempus=ut&vel=suscipit&pede=a&morbi=feugiat&porttitor=et&lorem=eros&id=vestibulum&ligula=ac&suspendisse=est&ornare=lacinia&consequat=nisi&lectus=venenatis&in=tristique&est=fusce&risus=congue&auctor=diam&sed=id&tristique=ornare&in=imperdiet&tempus=sapien&sit=urna&amet=pretium&sem=nisl&fusce=ut&consequat=volutpat&nulla=sapien&nisl=arcu&nunc=sed&nisl=augue&duis=aliquam&bibendum=erat&felis=volutpat&sed=in&interdum=congue&venenatis=etiam&turpis=justo&enim=etiam&blandit=pretium&mi=iaculis&in=justo&porttitor=in&pede=hac&justo=habitasse&eu=platea&massa=dictumst&donec=etiam&dapibus=faucibus&duis=cursus&at=urna&velit=ut&eu=tellus&est=nulla&congue=ut&elementum=erat&in=id&hac=mauris&habitasse=vulputate","creditScore":671,"rating":17},
    {"id":4,"first_name":"Conny","last_name":"Deniskevich","email":"cdeniskevich3@army.mil","gender":"Male","birthDate":"2/5/1999","web":"https://narod.ru/massa.html?diam=libero&neque=ut&vestibulum=massa&eget=volutpat&vulputate=convallis&ut=morbi&ultrices=odio&vel=odio&augue=elementum&vestibulum=eu&ante=interdum&ipsum=eu&primis=tincidunt&in=in","creditScore":266,"rating":14},
    {"id":5,"first_name":"Bentley","last_name":"Roman","email":"broman4@1und1.de","gender":"Male","birthDate":"7/5/1992","web":"http://army.mil/odio/justo/sollicitudin.jpg?natoque=nulla&penatibus=tellus&et=in&magnis=sagittis&dis=dui&parturient=vel&montes=nisl&nascetur=duis&ridiculus=ac&mus=nibh&etiam=fusce&vel=lacus&augue=purus&vestibulum=aliquet&rutrum=at&rutrum=feugiat&neque=non&aenean=pretium&auctor=quis&gravida=lectus&sem=suspendisse&praesent=potenti&id=in&massa=eleifend&id=quam&nisl=a&venenatis=odio&lacinia=in&aenean=hac&sit=habitasse&amet=platea&justo=dictumst&morbi=maecenas&ut=ut&odio=massa&cras=quis&mi=augue&pede=luctus&malesuada=tincidunt&in=nulla&imperdiet=mollis&et=molestie&commodo=lorem&vulputate=quisque&justo=ut&in=erat&blandit=curabitur&ultrices=gravida&enim=nisi&lorem=at&ipsum=nibh&dolor=in&sit=hac&amet=habitasse&consectetuer=platea&adipiscing=dictumst&elit=aliquam&proin=augue&interdum=quam&mauris=sollicitudin&non=vitae&ligula=consectetuer&pellentesque=eget&ultrices=rutrum&phasellus=at&id=lorem&sapien=integer&in=tincidunt&sapien=ante&iaculis=vel","creditScore":695,"rating":16},
    {"id":6,"first_name":"Rusty","last_name":"Kenworth","email":"rkenworth5@yahoo.com","gender":"Female","birthDate":"1/11/1996","web":"http://newyorker.com/integer/ac/leo/pellentesque/ultrices.png?curae=cubilia&mauris=curae&viverra=duis&diam=faucibus&vitae=accumsan&quam=odio&suspendisse=curabitur&potenti=convallis&nullam=duis&porttitor=consequat&lacus=dui&at=nec&turpis=nisi&donec=volutpat&posuere=eleifend&metus=donec&vitae=ut&ipsum=dolor&aliquam=morbi&non=vel&mauris=lectus&morbi=in&non=quam&lectus=fringilla&aliquam=rhoncus&sit=mauris&amet=enim&diam=leo&in=rhoncus&magna=sed&bibendum=vestibulum&imperdiet=sit&nullam=amet&orci=cursus&pede=id&venenatis=turpis&non=integer","creditScore":276,"rating":18},
    {"id":7,"first_name":"Angelita","last_name":"Borth","email":"aborth6@tinypic.com","gender":"Genderqueer","birthDate":"6/6/1997","web":"https://blog.com/rutrum/rutrum/neque.js?imperdiet=urna&sapien=pretium&urna=nisl&pretium=ut&nisl=volutpat&ut=sapien&volutpat=arcu&sapien=sed&arcu=augue&sed=aliquam&augue=erat&aliquam=volutpat&erat=in&volutpat=congue&in=etiam&congue=justo&etiam=etiam&justo=pretium&etiam=iaculis&pretium=justo&iaculis=in&justo=hac&in=habitasse&hac=platea&habitasse=dictumst&platea=etiam&dictumst=faucibus&etiam=cursus&faucibus=urna&cursus=ut&urna=tellus&ut=nulla&tellus=ut&nulla=erat&ut=id&erat=mauris&id=vulputate&mauris=elementum&vulputate=nullam&elementum=varius&nullam=nulla&varius=facilisi&nulla=cras&facilisi=non&cras=velit&non=nec&velit=nisi&nec=vulputate&nisi=nonummy&vulputate=maecenas&nonummy=tincidunt&maecenas=lacus&tincidunt=at","creditScore":442,"rating":17},
    {"id":8,"first_name":"Annadiana","last_name":"Linck","email":"alinck7@weibo.com","gender":"Male","birthDate":"10/14/1997","web":"http://techcrunch.com/sapien.html?accumsan=nec&odio=condimentum&curabitur=neque&convallis=sapien&duis=placerat&consequat=ante&dui=nulla&nec=justo&nisi=aliquam&volutpat=quis&eleifend=turpis&donec=eget&ut=elit&dolor=sodales&morbi=scelerisque&vel=mauris&lectus=sit&in=amet&quam=eros&fringilla=suspendisse&rhoncus=accumsan&mauris=tortor&enim=quis&leo=turpis&rhoncus=sed&sed=ante&vestibulum=vivamus&sit=tortor&amet=duis&cursus=mattis&id=egestas&turpis=metus&integer=aenean&aliquet=fermentum&massa=donec&id=ut&lobortis=mauris&convallis=eget&tortor=massa&risus=tempor&dapibus=convallis&augue=nulla&vel=neque&accumsan=libero&tellus=convallis&nisi=eget&eu=eleifend&orci=luctus&mauris=ultricies&lacinia=eu&sapien=nibh&quis=quisque&libero=id&nullam=justo&sit=sit&amet=amet&turpis=sapien&elementum=dignissim&ligula=vestibulum&vehicula=vestibulum&consequat=ante&morbi=ipsum","creditScore":272,"rating":6},
    {"id":9,"first_name":"Michele","last_name":"Oswald","email":"moswald8@ezinearticles.com","gender":"Male","birthDate":"5/18/1992","web":"http://acquirethisname.com/leo/odio/condimentum/id/luctus/nec/molestie.xml?aliquet=morbi&ultrices=vel&erat=lectus&tortor=in&sollicitudin=quam&mi=fringilla&sit=rhoncus&amet=mauris&lobortis=enim&sapien=leo&sapien=rhoncus&non=sed&mi=vestibulum&integer=sit&ac=amet&neque=cursus&duis=id&bibendum=turpis&morbi=integer&non=aliquet&quam=massa&nec=id&dui=lobortis&luctus=convallis&rutrum=tortor&nulla=risus&tellus=dapibus&in=augue&sagittis=vel&dui=accumsan&vel=tellus&nisl=nisi&duis=eu&ac=orci&nibh=mauris&fusce=lacinia&lacus=sapien&purus=quis&aliquet=libero&at=nullam&feugiat=sit&non=amet&pretium=turpis&quis=elementum&lectus=ligula&suspendisse=vehicula&potenti=consequat&in=morbi&eleifend=a&quam=ipsum&a=integer&odio=a&in=nibh&hac=in","creditScore":365,"rating":3},
    {"id":10,"first_name":"Adelaide","last_name":"Lutzmann","email":"alutzmann9@4shared.com","gender":"Male","birthDate":"11/5/1995","web":"http://123-reg.co.uk/mi/nulla/ac/enim/in.aspx?placerat=nisi&praesent=nam&blandit=ultrices&nam=libero&nulla=non&integer=mattis&pede=pulvinar&justo=nulla&lacinia=pede&eget=ullamcorper&tincidunt=augue&eget=a&tempus=suscipit&vel=nulla&pede=elit&morbi=ac&porttitor=nulla&lorem=sed&id=vel&ligula=enim&suspendisse=sit&ornare=amet&consequat=nunc&lectus=viverra&in=dapibus&est=nulla&risus=suscipit&auctor=ligula&sed=in&tristique=lacus&in=curabitur&tempus=at&sit=ipsum&amet=ac&sem=tellus&fusce=semper&consequat=interdum&nulla=mauris&nisl=ullamcorper&nunc=purus&nisl=sit&duis=amet&bibendum=nulla&felis=quisque&sed=arcu&interdum=libero&venenatis=rutrum&turpis=ac&enim=lobortis&blandit=vel&mi=dapibus&in=at","creditScore":779,"rating":16}];
 
//Task 1
function capNotFirstLetter(str){
    return str[0].toLowerCase() + str.substr(1,str.length).toUpperCase();
};

//Task 2
var data=people.map(p=>p);
for(var i=0;i<data.length;i++){
    data[i].first_name=capNotFirstLetter(data[i].first_name);
};

console.log(data);

//Task 3
var filteredByScore=data.filter(p=>p.creditScore>400);
console.log(filteredByScore);

//Task 4
data.sort(function(a,b){
    return new Date(a.birthDate)-new Date(b.birthDate);
});

console.log(data);